04.11.2022
// 51. Write a JavaScript program to get an object containing the parameters of the current URL. 



// 52. Write a JavaScript program to group the elements of a given array based on the given function. 



// 53. Write a JavaScript program to Initialize a two dimension array of given width and height and value. 



// 54. Write a JavaScript program to initialize an array containing the numbers in the specified range where start and end are inclusive with their common difference step.



// 55. Write a JavaScript program to Join all given URL segments together, then normalizes the resulting URL. 



// 56. Write a JavaScript program to check whether all elements in a given array are equal or not. 



// 57. Write a JavaScript program to compute the average of an array, after mapping each element to a value using the provided function. 



// 58. Write a JavaScript program to split values into two groups according to a predicate function, which specifies which group an element in the input collection belongs to. 



// 59. Write a JavaScript program to create a function that invokes fn with a given context, optionally adding any additional supplied parameters to the beginning of the arguments. 



// 60. Write a JavaScript program to create a function that invokes the method at a given key of an object, optionally adding any additional supplied parameters to the beginning of the arguments. 



// 61. Write a JavaScript program to cast the provided value as an array if it's not one. 



// 62. Write a JavaScript program to chain asynchronous functions. 



// 63. Write a JavaScript program to clone a given regular expression. 



// 64. Write a JavaScript program to get the first non-null / undefined argument. 



// 65. Write a JavaScript program to add special characters to text to print in color in the console (combined with console.log()). 



// 66. Write a JavaScript program to perform right-to-left function composition. 



// 67. Write a JavaScript program to perform left-to-right function composition. 



// 68. Write a JavaScript program that accepts a converging function and a list of branching functions and returns a function that applies each branching function to the arguments and the results of the branching functions are passed as arguments to the converging function. 



// 69. Write a JavaScript program to group the elements of an array based on the given function and returns the count of elements in each group. 



// 70. Write a JavaScript program to count the occurrences of a value in an array. 



// 71. Write a JavaScript program to create a deep clone of an object. 



// 72. Write a JavaScript program to detect whether the website is being opened in a mobile device or a desktop/laptop. 



// 73. Write a JavaScript program to return the difference between two arrays, after applying the provided function to each array element of both. 



// 74. Write a JavaScript program to filter out all values from an array for which the comparator function does not return true. 



// 75. Write a JavaScript program to compute the new ratings between two or more opponents using the Elo rating system. It takes an array of pre-ratings and returns an array containing post-ratings. The array should be ordered from best performer to worst performer (winner -> loser). 



// 76. Write a JavaScript program to execute a provided function once for each array element, starting from the array's last element.



// 77. Write a JavaScript program to iterate over all own properties of an object, running a callback for each one. 



// 78. Write a JavaScript program to invert the key-value pairs of an object, without mutating it. The corresponding inverted value of each inverted key is an array of keys responsible for generating the inverted value. If a function is supplied, it is applied to each inverted key. 



// 79. Write a JavaScript program to take any number of iterable objects or objects with a length property and returns the longest one. 



// 80. Write a JavaScript program to implement the Luhn Algorithm used to validate a variety of identification numbers, such as credit card numbers, IMEI numbers, National Provider Identifier numbers etc. 



// 81. Write a JavaScript program to create an object with keys generated by running the provided function for each key and the same values as the provided object. 



// 82. Write a JavaScript program to map the values of an array to an object using a function, where the key-value pairs consist of the original value as the key and the mapped value. 



// 83. Write a JavaScript program to create a new string with the results of calling a provided function on every character in the calling string. 



// 84. Write a JavaScript program to create an object with the same keys as the provided object and values generated by running the provided function for each value. 



// 85. Write a JavaScript program to replace all but the last number of characters with the specified mask character. 



// 86. Write a JavaScript program to get the maximum value of an array, after mapping each element to a value using the provided function. 



// 87. Write a JavaScript program to get the n maximum elements from the provided array. If n is greater than or equal to the provided array's length, then return the original array(sorted in descending order). 



// 88. Write a JavaScript program to get the median of an array of numbers. 



// 89. Write a JavaScript program to negates a predicate function.



// 90. Write a JavaScript program to nest a given flat array of objects linked to one another recursively. 



// 91. Write a JavaScript program that will return true if the provided predicate function returns false for all elements in a collection, false otherwise. 



// 92. Write a JavaScript program to create a function that gets the argument at index n. If n is negative, the nth argument from the end is returned. 



// 93. Write a JavaScript program to remove an event listener from an element. 



// 94. Write a JavaScript program to move the specified amount of elements to the end of the array. 



// 95. Write a JavaScript program to add an event listener to an element with the ability to use event delegation. 



// 96. Write a JavaScript program to pick the key-value pairs corresponding to the given keys from an object. 



// 97. Write a JavaScript program to create an object composed of the properties the given function returns truthy for. The function is invoked with two arguments: (value, key). 



// 98. Write a JavaScript program to filter an array of objects based on a condition while also filtering out unspecified keys. 



// 99. Write a JavaScript program to hash a given input string into a whole number. 



// 100. Write a JavaScript program to create an array of elements, grouped based on the position in the original arrays and using function as the last value to specify how grouped values should be combined. 

